/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package intervensim;

import com.sun.xml.internal.ws.api.message.Message;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Charles
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public GUI() {
        initComponents();
             // String appdata = System.getenv("APPDATA");
       // String iconPath = appdata + "\\Visualpharm-Icons8-Metro-Style-Medicine-Ambulance.ico";
        String iconPath = "C:\\Users\\Charles\\Documents\\NetBeansProjects\\Intervensim\\src\\image\\Visualpharm-Icons8-Metro-Style-Medicine-Ambulance.ico";
        ImageIcon imgicon = new ImageIcon(iconPath);
        this.setIconImage(imgicon.getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMap = new javax.swing.JPanel();
        jSlidZoom = new javax.swing.JSlider();
        jSlidVitesse = new javax.swing.JSlider();
        jLabZoom = new javax.swing.JLabel();
        jLabVitesse = new javax.swing.JLabel();
        jBtnDemarer = new javax.swing.JButton();
        jBtnPause = new javax.swing.JButton();
        jBtnStop = new javax.swing.JButton();
        jBtnDemarer1 = new javax.swing.JButton();
        jBtnDemarer2 = new javax.swing.JButton();
        jBtnDemarer3 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jBtnDemarer4 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jItemImporter = new javax.swing.JMenuItem();
        jItemSauvegarder = new javax.swing.JMenuItem();
        jItemQuitter = new javax.swing.JMenuItem();
        jMenuUrgence = new javax.swing.JMenu();
        jItemAjouterUrgence = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();
        jCbAfficherGrille = new javax.swing.JCheckBoxMenuItem();
        jItemOptionAvance = new javax.swing.JMenuItem();
        jMenuAide = new javax.swing.JMenu();
        jMenuPropos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Intervensim");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelMap.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanelMap);
        jPanelMap.setBounds(0, 0, 560, 360);

        jSlidZoom.setMajorTickSpacing(10);
        jSlidZoom.setMinimum(1);
        jSlidZoom.setMinorTickSpacing(2);
        jSlidZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlidZoomStateChanged(evt);
            }
        });
        jSlidZoom.setValue(1);
        getContentPane().add(jSlidZoom);
        jSlidZoom.setBounds(260, 370, 200, 23);

        jSlidVitesse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlidVitesseStateChanged(evt);
            }
        });
        jSlidVitesse.setValue(0);
        getContentPane().add(jSlidVitesse);
        jSlidVitesse.setBounds(260, 400, 200, 23);

        jLabZoom.setText("Zoom: 1x");
        getContentPane().add(jLabZoom);
        jLabZoom.setBounds(460, 370, 100, 20);

        jLabVitesse.setText("Vitesse: 1x");
        getContentPane().add(jLabVitesse);
        jLabVitesse.setBounds(460, 400, 100, 20);

        jBtnDemarer.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDemarer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Media-Controls-Play-icon.png"))); // NOI18N
        jBtnDemarer.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnDemarer);
        jBtnDemarer.setBounds(20, 380, 40, 40);

        jBtnPause.setBackground(new java.awt.Color(204, 204, 204));
        jBtnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Media-Controls-Pause-icon.png"))); // NOI18N
        jBtnPause.setPreferredSize(new java.awt.Dimension(50, 50));
        jBtnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPauseActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPause);
        jBtnPause.setBounds(60, 380, 40, 40);

        jBtnStop.setBackground(new java.awt.Color(204, 204, 204));
        jBtnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Media-Controls-Stop-icon.png"))); // NOI18N
        jBtnStop.setToolTipText("");
        jBtnStop.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnStop);
        jBtnStop.setBounds(100, 380, 40, 40);

        jBtnDemarer1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDemarer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medicine-Ambulance-icon.png"))); // NOI18N
        jBtnDemarer1.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnDemarer1);
        jBtnDemarer1.setBounds(570, 130, 60, 60);

        jBtnDemarer2.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDemarer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Charts-Mind-map-icon.png"))); // NOI18N
        jBtnDemarer2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnDemarer2);
        jBtnDemarer2.setBounds(570, 10, 60, 60);

        jBtnDemarer3.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDemarer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Image-Edition-Tools-Line-icon.png"))); // NOI18N
        jBtnDemarer3.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnDemarer3);
        jBtnDemarer3.setBounds(570, 70, 60, 60);

        label1.setText("Ajouter un port d'attache");
        getContentPane().add(label1);
        label1.setBounds(630, 130, 140, 60);

        label2.setText("Ajouter un noeud");
        getContentPane().add(label2);
        label2.setBounds(630, 10, 140, 60);

        label3.setText("Ajouter un segment");
        getContentPane().add(label3);
        label3.setBounds(630, 70, 140, 60);

        jBtnDemarer4.setBackground(new java.awt.Color(204, 204, 204));
        jBtnDemarer4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Maps-and-Geolocation-Polyline-icon.png"))); // NOI18N
        jBtnDemarer4.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jBtnDemarer4);
        jBtnDemarer4.setBounds(570, 190, 60, 60);

        label4.setText("Ajout rapide");
        getContentPane().add(label4);
        label4.setBounds(630, 190, 140, 60);

        jMenuFichier.setText("Fichier");

        jItemImporter.setText("Importer une simulation");
        jMenuFichier.add(jItemImporter);

        jItemSauvegarder.setText("Sauvegarder une simulation");
        jMenuFichier.add(jItemSauvegarder);

        jItemQuitter.setText("Quitter");
        jItemQuitter.setActionCommand("jMenuQuitter");
        jItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemQuitterActionPerformed(evt);
            }
        });
        jMenuFichier.add(jItemQuitter);

        jMenuBar.add(jMenuFichier);

        jMenuUrgence.setText("Urgence");

        jItemAjouterUrgence.setText("Ajouter une urgence");
        jMenuUrgence.add(jItemAjouterUrgence);

        jMenuBar.add(jMenuUrgence);

        jMenuOptions.setText("Options");

        jCbAfficherGrille.setSelected(true);
        jCbAfficherGrille.setText("Affichier la grille");
        jMenuOptions.add(jCbAfficherGrille);

        jItemOptionAvance.setText("Options avancés");
        jItemOptionAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemOptionAvanceActionPerformed(evt);
            }
        });
        jMenuOptions.add(jItemOptionAvance);

        jMenuBar.add(jMenuOptions);

        jMenuAide.setText("Aide");
        jMenuBar.add(jMenuAide);

        jMenuPropos.setText("À propos");
        jMenuBar.add(jMenuPropos);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemQuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItemQuitterActionPerformed

    private void jItemOptionAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemOptionAvanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItemOptionAvanceActionPerformed

    private void jBtnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPauseActionPerformed

    private void jSlidZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlidZoomStateChanged
        // TODO add your handling code here:
       jLabZoom.setText("Zoom: " + String.valueOf(jSlidZoom.getValue()) + "x");
    }//GEN-LAST:event_jSlidZoomStateChanged

    private void jSlidVitesseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlidVitesseStateChanged
        // TODO add your handling code here:
         jLabVitesse.setText("Vitesse: " + String.valueOf(jSlidVitesse.getValue()) + "x");
    }//GEN-LAST:event_jSlidVitesseStateChanged

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode())
        {
                case 1: ;
                
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDemarer;
    private javax.swing.JButton jBtnDemarer1;
    private javax.swing.JButton jBtnDemarer2;
    private javax.swing.JButton jBtnDemarer3;
    private javax.swing.JButton jBtnDemarer4;
    private javax.swing.JButton jBtnPause;
    private javax.swing.JButton jBtnStop;
    private javax.swing.JCheckBoxMenuItem jCbAfficherGrille;
    private javax.swing.JMenuItem jItemAjouterUrgence;
    private javax.swing.JMenuItem jItemImporter;
    private javax.swing.JMenuItem jItemOptionAvance;
    private javax.swing.JMenuItem jItemQuitter;
    private javax.swing.JMenuItem jItemSauvegarder;
    private javax.swing.JLabel jLabVitesse;
    private javax.swing.JLabel jLabZoom;
    private javax.swing.JMenu jMenuAide;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JMenu jMenuPropos;
    private javax.swing.JMenu jMenuUrgence;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JSlider jSlidVitesse;
    private javax.swing.JSlider jSlidZoom;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
